# Generated by Django 4.0 on 2022-04-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_user_is_donor_alter_user_is_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleList',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('myself', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myself', to='accounts.user')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
