# Generated by Django 4.0 on 2022-04-01 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='peoplelist',
            name='people',
        ),
        migrations.AddField(
            model_name='peoplelist',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
