# Generated by Django 4.0 on 2022-05-06 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('friend', '0002_remove_friendrequest_reciever_friendrequest_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_list', models.ManyToManyField(blank=True, related_name='groups', to='friend.Group')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='accounts.user')),
            ],
        ),
    ]
