# Generated by Django 4.0.1 on 2022-01-09 15:01

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=40, verbose_name='last name')),
                ('mobile', models.CharField(blank=True, max_length=13, verbose_name='mobile')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_student', models.BooleanField(default=False, verbose_name='is student')),
                ('is_mentor', models.BooleanField(default=False, verbose_name='is teacher')),
                ('is_tutor', models.BooleanField(default=False, verbose_name='is librarian')),
                ('is_donor', models.BooleanField(default=False, verbose_name='is librarian')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('standard', models.IntegerField()),
                ('institute', models.CharField(max_length=200, null=True)),
                ('requiresDonation', models.BooleanField(default=True)),
                ('requiresMentor', models.BooleanField(default=True)),
                ('requiresTutor', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
