# Generated by Django 4.0.1 on 2022-01-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mentor_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience_in_years', models.IntegerField()),
                ('subject', models.ManyToManyField(related_name='tutors', to='accounts.Subject')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
