# Generated by Django 4.0.1 on 2022-01-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='subject',
            new_name='subjects',
        ),
    ]
