# Generated by Django 4.0.1 on 2022-01-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_subject_tutor_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='subjects',
            new_name='subject',
        ),
    ]
