# Generated by Django 4.0.1 on 2022-01-09 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_subjects_tutor_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('donation_type', models.CharField(choices=[('monthly', 'monthly'), ('annual', 'annual')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
