# Generated by Django 4.0.1 on 2022-01-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subject',
        ),
        migrations.AddField(
            model_name='tutor',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='accounts.subject'),
            preserve_default=False,
        ),
    ]
