# Generated by Django 4.0.1 on 2022-01-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_tutor_subject_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='accounts.subject'),
        ),
    ]
