# Generated by Django 4.0.1 on 2022-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_tutor_subject_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_donor',
            field=models.BooleanField(default=False, verbose_name='is donor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='is mentor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='is tutor'),
        ),
    ]
